name: Deploy to production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create SSH key and push to bare repo
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_USER: ${{vars.SSH_USER}}
          SSH_HOST: ${{vars.SSH_HOST}}
          REMOTE_PATH: ${{vars.REMOTE_PATH}}
          SSH_KEY_PATH: ~/.ssh/private.key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > $SSH_KEY_PATH
          chmod 600 $SSH_KEY_PATH
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          GIT_SSH_COMMAND="ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_HOST" git push ssh://$SSH_USER@$SSH_HOST/$REMOTE_PATH main
        shell: bash
